name: Set up ZKVM toolchains and Rust
description: Set up ZKVM toolchains and Rust
inputs:
    pull_token:
        description: "Token to use for private repo access"
        required: true
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - name: Install cargo-risczero
          uses: taiki-e/install-action@v2
          with:
              tool: cargo-risczero@0.20
        - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
          shell: bash
          run: make install-risc0-toolchain
          env:
              GITHUB_TOKEN: ${{ inputs.pull_token }}
        - name: Install SP1 toolchain
          shell: bash
          env:
              SHELL: /bin/bash
          run: |
              curl -L https://sp1.succinct.xyz | bash
              ~/.sp1/bin/sp1up
              ~/.sp1/bin/cargo-prove prove --version
              ~/.sp1/bin/cargo-prove prove install-toolchain
              pwd
        - name: Install Rust
          shell: bash
          run: rustup show && rustup install nightly && rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
