//! The `sov-sequencer-registry` module is responsible for sequencer
//! registration, slashing, and rewards. At the moment, only a centralized
//! sequencer is supported. The sequencer's address and bond are registered
//! during the rollup deployment.
//!
//! The module implements the [`sov_modules_api::hooks::ApplyBatchHooks`] trait.

#![deny(missing_docs)]
mod call;
mod event;
mod genesis;
mod hooks;
#[cfg(feature = "native")]
mod rpc;
use borsh::{BorshDeserialize, BorshSerialize};
pub use call::*;
pub use genesis::*;
#[cfg(feature = "native")]
pub use rpc::*;
use serde::{Deserialize, Serialize};
use sov_bank::{Amount, Coins};
use sov_modules_api::{
    CallResponse, Context, Error, ModuleInfo, Spec, StateAccessor, StateCheckpoint, StateMap,
    StateValue, WorkingSet,
};
use sov_state::codec::BcsCodec;

use crate::event::Event;

/// An allowed sequencer for a rollup.
#[derive(Debug, Clone, Serialize, Deserialize, BorshSerialize, BorshDeserialize, Eq, PartialEq)]
#[serde(bound = "S::Address: serde::Serialize + serde::de::DeserializeOwned")]
pub(crate) struct AllowedSequencer<S: Spec> {
    /// The rollup address of the sequencer.
    pub rollup_address: S::Address,
    /// The staked balance of the sequencer.
    pub balance: Amount,
}

/// The `sov-sequencer-registry` module `struct`.
#[cfg_attr(feature = "native", derive(sov_modules_api::ModuleCallJsonSchema))]
#[derive(Clone, ModuleInfo)]
pub struct SequencerRegistry<S: Spec, Da: sov_modules_api::DaSpec> {
    /// The address of the `sov_sequencer_registry` module.
    /// Note: this is address is generated by the module framework and the
    /// corresponding private key is unknown.
    #[address]
    pub(crate) address: S::Address,

    /// Reference to the Bank module.
    #[module]
    pub(crate) bank: sov_bank::Bank<S>,

    /// Only batches from sequencers from this list are going to be processed.
    #[state]
    pub(crate) allowed_sequencers: StateMap<Da::Address, AllowedSequencer<S>, BcsCodec>,

    /// Optional preferred sequencer.
    /// If set, batches from this sequencer will be processed first in block,
    /// So this sequencer can guarantee soft confirmation time for transactions
    #[state]
    pub(crate) preferred_sequencer: StateValue<Da::Address, BcsCodec>,

    /// Coin's that will be slashed if the sequencer is malicious.
    /// The coins will be transferred from
    /// [`SequencerConfig::seq_rollup_address`] to
    /// [`SequencerRegistry::address`] and locked forever, until sequencer
    /// decides to exit (unregister).
    ///
    /// Only sequencers in the [`SequencerRegistry::allowed_sequencers`] list are
    /// allowed to exit.
    #[state]
    pub(crate) coins_to_lock: StateValue<Coins<S>>,
}

/// Result of applying a blob, from sequencer's point of view.
pub enum SequencerOutcome<Da: sov_modules_api::DaSpec> {
    /// The blob was applied successfully and the operation is concluded.
    Rewarded {
        /// The number of tokens to award
        amount: u64,
    },
    /// The sequencer incurred a net penalty as a result of invalid (but not provably malicious) trabsactions.
    Penalized {
        /// The number of tokens to confiscate
        amount: u64,
    },
    /// The blob was *not* applied successfully. The sequencer has been slashed
    /// as a result of the invalid blob.
    Slashed {
        /// The address of the sequencer that was slashed.
        sequencer: Da::Address,
    },
}

impl<S: Spec, Da: sov_modules_api::DaSpec> sov_modules_api::Module for SequencerRegistry<S, Da> {
    type Spec = S;

    type Config = SequencerConfig<S, Da>;

    type CallMessage = CallMessage;

    type Event = Event;

    fn genesis(&self, config: &Self::Config, working_set: &mut WorkingSet<S>) -> Result<(), Error> {
        Ok(self.init_module(config, working_set)?)
    }

    fn call(
        &self,
        message: Self::CallMessage,
        context: &Context<Self::Spec>,
        working_set: &mut WorkingSet<S>,
    ) -> Result<CallResponse, Error> {
        Ok(match message {
            CallMessage::Register { da_address, amount } => {
                let da_address = Da::Address::try_from(&da_address)?;
                self.register(&da_address, amount, context, working_set)?
            }
            CallMessage::Deposit { da_address, amount } => {
                let da_address = Da::Address::try_from(&da_address)?;
                self.increase_sender_balance(&da_address, amount, working_set)?
            }
            CallMessage::Exit { da_address } => {
                let da_address = Da::Address::try_from(&da_address)?;
                self.exit(&da_address, context, working_set)?
            }
        })
    }
}

impl<S: Spec, Da: sov_modules_api::DaSpec> SequencerRegistry<S, Da> {
    /// Returns the configured amount of [Coins] to lock.
    pub fn get_coins_to_lock(&self, working_set: &mut impl StateAccessor) -> Coins<S> {
        self.coins_to_lock.get(working_set).expect(
            "The coins to lock is set and genesis and must always be available. This is a bug!",
        )
    }

    pub(crate) fn register_sequencer(
        &self,
        da_address: &Da::Address,
        rollup_address: &S::Address,
        amount: Amount,
        working_set: &mut WorkingSet<S>,
    ) -> anyhow::Result<()> {
        if amount == 0 {
            anyhow::bail!(
                "The provided initial balance `{}` for the sequencer `{}` is zero.",
                amount,
                da_address
            );
        }

        if self
            .allowed_sequencers
            .get(da_address, working_set)
            .is_some()
        {
            anyhow::bail!("sequencer {} already registered", rollup_address)
        }
        let locker = &self.address;
        let mut coins = self.get_coins_to_lock(working_set);

        coins.amount = amount;

        self.bank
            .transfer_from(rollup_address, locker, coins, working_set)?;

        self.allowed_sequencers.set(
            da_address,
            &AllowedSequencer {
                rollup_address: rollup_address.clone(),
                balance: amount,
            },
            working_set,
        );

        Ok(())
    }

    /// Returns the preferred sequencer, or [`None`] it wasn't set.
    ///
    /// Read about [`SequencerConfig::is_preferred_sequencer`] to learn about
    /// preferred sequencers.
    pub fn get_preferred_sequencer(
        &self,
        working_set: &mut impl StateAccessor,
    ) -> Option<Da::Address> {
        self.preferred_sequencer.get(working_set)
    }

    /// Resolve a DA address to a rollup address.
    pub fn resolve_da_address(
        &self,
        address: &Da::Address,
        working_set: &mut impl StateAccessor,
    ) -> Option<S::Address> {
        self.allowed_sequencers
            .get(address, working_set)
            .map(|s| s.rollup_address)
    }

    /// Returns the rollup address of the preferred sequencer, or [`None`] it wasn't set.
    ///
    /// Read about [`SequencerConfig::is_preferred_sequencer`] to learn about
    /// preferred sequencers.
    pub fn get_preferred_sequencer_rollup_address(
        &self,
        working_set: &mut impl StateAccessor,
    ) -> Option<S::Address> {
        self.preferred_sequencer.get(working_set).map(|da_addr| {
            self.allowed_sequencers
                .get(&da_addr, working_set)
                .expect("Preferred Sequencer must have known address on rollup")
                .rollup_address
        })
    }

    /// Update the amount of coins to stake.
    ///
    /// Will override only the coins amount, leaving the token address intact.
    ///
    /// To ensure the impracticability of protocol-level attacks, a sufficient stake is required.
    /// One such expense includes the cost for transaction deserialization and signature
    /// verification, which, in the worst-case scenario, the sequencer must bear. Consequently, the
    /// staked amount must be commensurate with a worst-case block scenario comprised of the
    /// maximum possible transaction count, all of which fall under this category.
    ///
    /// The allowed list of sequencers will be affected, as those with insufficient balance to meet
    /// the new locking requirement will be unable to submit blocks. This could potentially lead to
    /// a full rollup lock if no sequencer maintains an adequate balance. To ensure the continuous
    /// submission of blocks, there should always be at least one sequencer with sufficient
    /// balance. Use this functionality with caution.
    pub fn set_coins_amount_to_lock(
        &self,
        amount: Amount,
        working_set: &mut impl StateAccessor,
    ) -> anyhow::Result<()> {
        let mut coins_to_lock = self.get_coins_to_lock(working_set);

        coins_to_lock.amount = amount;
        self.coins_to_lock.set(&coins_to_lock, working_set);

        Ok(())
    }

    /// Checks whether `sender` is a registered sequencer with enough staked amount.
    pub fn is_sender_allowed(
        &self,
        sender: &Da::Address,
        working_set: &mut impl StateAccessor,
    ) -> bool {
        let balance = match self.allowed_sequencers.get(sender, working_set) {
            Some(a) => a.balance,
            None => return false,
        };

        let amount = self
            .coins_to_lock
            .get(working_set)
            .expect(
                "The coins to lock is set and genesis and must always be available. This is a bug!",
            )
            .amount;
        if balance < amount {
            return false;
        }

        true
    }

    /// Returns the balance of the provided sender, if present.
    pub fn get_sender_balance(
        &self,
        sender: &Da::Address,
        working_set: &mut WorkingSet<S>,
    ) -> Option<Amount> {
        self.allowed_sequencers
            .get(sender, working_set)
            .map(|s| s.balance)
    }

    /// Slash the sequencer with the given address.
    pub fn slash_sequencer(&self, da_address: &Da::Address, working_set: &mut StateCheckpoint<S>) {
        self.delete(da_address, working_set);
    }
}
