pub mod display;
#[cfg(feature = "serde")]
pub mod json_to_borsh;
pub mod schema;
pub mod ty;

pub extern crate bech32;

#[cfg(feature = "macros")]
/// Implements the [`SchemaGenerator`](schema::SchemaGenerator) trait for the
/// annotated struct or enum.
///
/// The schema generated by the trait allows two main features.
/// First, the borsh-encoding of the type to be dispalyed in a human-readable format, with the exact
/// formatting controlled by attributes on the fields of the type.
/// Second, it allows a JSON-encoding of the type to be translated into borsh-encoding, without
/// needing access to the original Rust definition of the type.
///
/// ## Attributes: `#[sov_wallet(bound = "T: Trait")]`
///
/// Tells the proc-macro to add the specified bound to the where clause
/// of the generated implementation instead of adding the default `T: SchemaGenerator` (where `T`
/// is the type of the annotated field).
///
/// This annotation may only be applied to fields, not items.
///
/// ## Attributes: #[sov_wallet(hidden)]`
///
/// Causes the field to be hidden from the user during display. This is often used for data
/// that can't be displayed in a human-readable format, such as merkle proofs. If the field is not
/// present in the `borsh` serialization of the type, use `#[sov_wallet(skip)]` instead.
///
/// This annotation may only be applied to fields, not items.
///
/// ```rust
/// use sov_rollup_interface::sov_universal_wallet::{schema::Schema, UniversalWallet};
/// #[derive(UniversalWallet, borsh::BorshSerialize)]
/// pub struct Unreadable {
///    name: String,
///    #[sov_wallet(hidden)]
///    opaque_contents: Vec<u8>,
/// }
/// let serialized = borsh::to_vec(&Unreadable { name: "foo.txt".to_string(), opaque_contents: vec![23, 74, 119, 119, 2, 232, 22]}).unwrap();
/// assert_eq!(Schema::of_single_type::<Unreadable>().display(0, &serialized).unwrap(), r#"{ name: "foo.txt" }"#);
/// ```
///
/// ## Attributes: `#[sov_wallet(as_ty = "path::to::Type")]`
///
/// Inserts the schema of the specified type in place of the schema for the annotated field. Note that the subsituted type
/// must have exactly the same borsh serialization as the original.
///
/// This is useful when you want to display a foreign type that doesn't implement [`SchemaGenerator`](schema::SchemaGenerator),
/// or when you want to override the default schema for a type in a particular context.
///
/// ```rust
/// use sov_rollup_interface::sov_universal_wallet::{schema::Schema, UniversalWallet};
///
/// // A foreign type that doesn't derive UniversalWallet
/// #[derive(borsh::BorshSerialize)]
/// pub struct Foreign(String);
///
/// #[derive(UniversalWallet, borsh::BorshSerialize)]
/// pub struct Tagged {
///    #[sov_wallet(as_ty = "String")]
///    data: Foreign,
///    tag: String,
/// }
/// let serialized = borsh::to_vec(&Tagged { data: Foreign("foo".to_string()), tag: "world".to_string()}).unwrap();
/// assert_eq!(Schema::of_single_type::<Tagged>().display(0, &serialized).unwrap(), r#"{ data: "foo", tag: "world" }"#);
/// ```
///
/// ## Attributes: `#[sov_wallet(skip)]`
///
/// Causes the field to be excluded from the Schema entirely. This should be used if the field is not present in
/// the `borsh` serialization of the type. If the type is present in the serialization but should not be displayed,
/// use `#[sov_wallet(hidden)]` instead.
///
/// ```rust
/// use sov_rollup_interface::sov_universal_wallet::{schema::Schema, UniversalWallet};
/// #[derive(UniversalWallet, borsh::BorshSerialize)]
/// pub struct File {
///     #[borsh(skip)]
///     #[sov_wallet(skip)]
///     checksum: Option<[u8;32]>,
///     contents: Vec<u8>,
/// }
/// let serialized = borsh::to_vec(&File { contents: vec![1, 2, 3], checksum: None }).unwrap();
/// assert_eq!(Schema::of_single_type::<File>().display(0, &serialized).unwrap(), r#"{ contents: 0x010203 }"#);
/// ```
///
/// ## Attributes: `#[sov_wallet(display({encoding}))]`
///
/// Specifies the encoding to use when displaying a byte sequence or integer. The encoding can be one of the following:
/// - hex: displays the type as a hexadecimal string with the prefix "0x"
/// - decimal: displays the type as a decimal number (integer only) or a list of decimal numbers in square brackets (byte sequence)
/// - bech32(prefix = "my_prefix_expr"): displays the type as a bech32-encoded string with the specified human-readable part. (byte sequence only)
/// - bech32m(prefix = "my_prefix_expr"): displays the type as a bech32-encoded string with the specified human-readable part. (byte sequence only)
///
/// This annotation may only be applied to fields, not items. The field must have type integer, `[u8;N]`, or `Vec<u8>` to use this attribute.
///
/// ```rust
/// use sov_rollup_interface::sov_universal_wallet::{schema::Schema, UniversalWallet};
///
/// fn prefix() -> &'static str {
///   "celestia"
/// }
///
/// #[derive(UniversalWallet, borsh::BorshSerialize)]
/// pub struct CelestiaAddress(
///   #[sov_wallet(display(bech32(prefix = "prefix()")))]
///   [u8;32],
/// );
/// let serialized = borsh::to_vec(&CelestiaAddress([1; 32])).unwrap();
/// assert_eq!(Schema::of_single_type::<CelestiaAddress>().display(0, &serialized).unwrap(), "celestia1qyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqsagv2r7");
/// ```
pub use sov_universal_wallet_macros::UniversalWallet;
