//! A client for the Sovereign SDK sequencer JSON API, generated by
//! [`progenitor`].

progenitor::generate_api!(
    spec = "../sov-sequencer/openapi-v3.yaml",
    derives = [Debug, Clone, PartialEq, Eq],
);
