//! A client for the Sovereign SDK rollup JSON API, generated by
//! [`progenitor`].

pub extern crate tokio_tungstenite;

progenitor::generate_api!(
    spec = "../sov-api-spec/openapi-v3.yaml",
    derives = [Debug, Clone, PartialEq],
);
