services:
  validator:
    image: validator
    hostname: validator
    build:
      context: .
      dockerfile: Dockerfile.validator
    healthcheck:
      # To see healthcheck output:
      # docker inspect --format "{{json .State.Health }}" docker-validator-1 | jq
      test: [ "CMD", "curl", "-s", "-f", "http://127.0.0.1:26657/health" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    # uncomment to provide amount of sequencers to provision (default: 1)
    # command: [ "/opt/entrypoint.sh", "2" ]
    volumes:
      - credentials:/credentials
      - genesis:/genesis
    networks:
      - monitoring-network

  sequencer-0:
    image: bridge
    hostname: sequencer-0
    build:
      context: .
      dockerfile: Dockerfile.bridge
    depends_on:
      - validator
    healthcheck:
      # To see healthcheck output:
      # docker inspect --format "{{json .State.Health }}" docker-sequencer-0-1 | jq
      test: [ "CMD", "/opt/bridge-healthcheck.sh", "/credentials/bridge-0.jwt" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s
    # uncomment to provide the id of the sequencer (default: 0)
    # command: ["/opt/entrypoint.sh", "0"]
    ports:
      - 26658:26658
    volumes:
      - credentials:/credentials:consistent
      - genesis:/genesis
    networks:
      - monitoring-network

#  #   Uncomment for another sequencer
#  #   remember to adjust services.validator.command
#  sequencer-1:
#    image: bridge
#    build:
#      context: .
#      dockerfile: Dockerfile.bridge
#    depends_on:
#      - validator
#    healthcheck:
#      test: [ "CMD", "/opt/bridge-healthcheck.sh", "/credentials/bridge-1.jwt" ]
#      interval: 10s
#      timeout: 5s
#      retries: 30
#      start_period: 10s
#    # The first argument is the id of the sequencer (default: 0)
#    command: [ "/opt/entrypoint.sh", "1" ]
#    ports:
#      # remap the default port as it's already used
#      - 36658:26658
#    volumes:
#      - credentials:/credentials:consistent
#      - genesis:/genesis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    profiles:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    depends_on:
      - prometheus
    profiles:
      - monitoring
    networks:
      - monitoring-network

volumes:
  # local volume where sequencer's credentials can persist
  credentials:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./credentials"
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  monitoring-network:
    driver: bridge