use sov_bank::{BankConfig, GasTokenConfig, TokenId};
use sov_modules_api::test_utils::generate_address as gen_address_generic;
use sov_modules_api::Spec;
use sov_test_utils::runtime::genesis::optimistic::HighLevelOptimisticGenesisConfig;
use sov_test_utils::runtime::genesis::TestTokenName;
use sov_test_utils::runtime::TestRunner;
use sov_test_utils::{generate_optimistic_runtime, MockDaSpec, TestUser};

type S = sov_test_utils::TestSpec;

// This code is not actually dead; rustc treats each test file as a separate crate
// so this code looks unused during some of the compilations.
pub fn generate_address(name: &str) -> <S as Spec>::Address {
    gen_address_generic::<S>(name)
}

pub fn create_bank_config_with_token(
    addresses_count: usize,
    initial_balance: u64,
) -> BankConfig<S> {
    let address_and_balances = (0..addresses_count)
        .map(|i| {
            let key = format!("key_{}", i);
            let addr = generate_address(&key);
            (addr, initial_balance)
        })
        .collect();

    let token_name = "InitialToken".to_owned();

    BankConfig {
        gas_token_config: GasTokenConfig {
            token_name,
            address_and_balances,
            authorized_minters: vec![],
        },
        tokens: vec![],
    }
}

generate_optimistic_runtime!(TestBankRuntime <=);

/// The default runtime type used in the bank tests.
pub type RT = TestBankRuntime<S, MockDaSpec>;

/// A handful of useful test roles generated by the [`setup`] function.
pub struct TestData {
    /// A specific token ID used in the tests.
    pub token_name: TestTokenName,
    /// The token ID associated with [`Self::token_name`].
    pub token_id: TokenId,
    /// A user with a high token balance of [`Self::token_id`].
    pub user_high_token_balance: TestUser<S>,
    /// A user with no token balance of [`Self::token_id`].
    pub user_no_token_balance: TestUser<S>,
}

/// Sets up the bank tests by generating a genesis config with a single non-default token that has
/// - a minter
/// - a user with a high token balance
/// - a user with no balance for the token
pub fn setup() -> (TestData, TestRunner<RT, S>) {
    let token_name = TestTokenName::new("BankToken".to_string());
    let token_id = token_name.id();

    let genesis_config = HighLevelOptimisticGenesisConfig::generate_with_additional_accounts(1)
        .add_accounts_with_token(&token_name, true, 1, 100_000);

    let user_no_token_balance = genesis_config.additional_accounts[0].clone();

    let mut token_users_vec = genesis_config.get_accounts_for_token(&token_name);

    let user_high_token_balance = token_users_vec.pop().unwrap();

    let genesis = GenesisConfig::from_minimal_config(genesis_config.into());

    let runner = TestRunner::new_with_genesis(genesis.into_genesis_params(), RT::default());

    (
        TestData {
            token_name,
            token_id,
            user_high_token_balance,
            user_no_token_balance,
        },
        runner,
    )
}
