//! A client for the Sovereign SDK ledger JSON API, generated by
//! [`progenitor`].

progenitor::generate_api!(
    spec = "../sov-ledger-apis/openapi-v3.yaml",
    derives = [Debug, Clone, PartialEq],
);
