{
 "title": "Sovereign Rollup Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Processsing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DA Blocks Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "da_blocks_processed_count",
     "legendFormat": "{{instance}} {{ $__rate_interval }}"
    }
   ]
  },
  {
   "title": "DA Blocks Processed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "rate(da_blocks_processed_count[$__rate_interval])",
     "legendFormat": "{{instance}} {{ $__rate_interval }}"
    }
   ]
  },
  {
   "title": "Batches Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "rollup_batches_processed_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transactions Processed per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(rollup_txns_processed_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(process_slot_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} 95th p"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(process_slot_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} median"
    }
   ]
  },
  {
   "title": "STF transition times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(stf_transition_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} 95th p"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(stf_transition_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} median"
    }
   ]
  },
  { "title": "Data Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sync_distance", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Sync distance rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "abs(delta(sync_distance[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current DA Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    { "expr": "current_da_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transactions per DA Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    { "expr": "rollup_txns_per_da_block", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Schema DB get bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(schemadb_get_bytes_sum[$__rate_interval])",
     "legendFormat": "{{cf_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Schema DB batch commit bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(schemadb_batch_commit_bytes_sum[$__rate_interval])",
     "legendFormat": "{{db_name}}@{{instance}}"
    }
   ]
  }
 ]
}