#![deny(missing_docs)]
#![doc = include_str!("../README.md")]

mod capabilities;

#[cfg(feature = "native")]
mod rpc;

use borsh::{BorshDeserialize, BorshSerialize};
#[cfg(feature = "native")]
pub use rpc::*;
use serde::{Deserialize, Serialize};
use sov_chain_state::TransitionHeight;
use sov_modules_api::batch::BatchWithId;
use sov_modules_api::macros::config_constant;
use sov_modules_api::tx_verifier::RawTx;
use sov_modules_api::{
    KernelModule, KernelModuleInfo, KernelStateValue, KernelWorkingSet, StateCheckpoint, StateMap,
    StateMapAccessor,
};
use sov_state::codec::BcsCodec;

/// For how many slots deferred blobs are stored before being executed
#[config_constant]
pub const DEFERRED_SLOTS_COUNT: u64;

/// The sequence number for a batch from the preferred sequencer.   
pub type SequenceNumber = u64;

/// Blob storage contains only address and vector of blobs
#[derive(Clone, KernelModuleInfo)]
pub struct BlobStorage<S: sov_modules_api::Spec, Da: sov_modules_api::DaSpec> {
    /// The address of blob storage module
    /// Note: this is address is generated by the module framework and the corresponding private key is unknown.
    #[address]
    pub(crate) address: S::Address,

    /// Actual storage of blobs
    /// DA block number => vector of blobs
    /// Caller controls the order of blobs in the vector
    #[state]
    pub(crate) deferred_blobs: StateMap<u64, Vec<(BatchWithId, Da::Address)>, BcsCodec>,

    /// Any preferred sequencer blobs which were received out of order. Mapped from sequence number to batch.
    #[state]
    pub(crate) deferred_preferred_sequencer_blobs: StateMap<SequenceNumber, PreferredBatchWithId>,

    /// The next sequence number for the preferred sequencer. This is used to determine if a batch is out of order.
    #[state]
    next_sequence_number: KernelStateValue<SequenceNumber>,

    #[module]
    pub(crate) sequencer_registry: sov_sequencer_registry::SequencerRegistry<S, Da>,

    #[kernel_module]
    chain_state: sov_chain_state::ChainState<S, Da>,
}

/// Non standard methods for blob storage
impl<S: sov_modules_api::Spec, Da: sov_modules_api::DaSpec> BlobStorage<S, Da> {
    /// Store blobs for given block number, overwrite if already exists
    pub fn store_batches(
        &self,
        slot_number: TransitionHeight,
        batches: &Vec<(BatchWithId, Da::Address)>,
        working_set: &mut StateCheckpoint<S>,
    ) {
        self.deferred_blobs.set(&slot_number, batches, working_set);
    }

    /// Take all blobs for given block number, return empty vector if not exists
    /// Returned blobs are removed from the storage
    pub fn take_blobs_for_slot_number(
        &self,
        slot_height: TransitionHeight,
        working_set: &mut StateCheckpoint<S>,
    ) -> Vec<(BatchWithId, Da::Address)> {
        self.deferred_blobs
            .remove(&slot_height, working_set)
            .unwrap_or_default()
    }

    pub(crate) fn get_preferred_sequencer(
        &self,
        working_set: &mut StateCheckpoint<S>,
    ) -> Option<Da::Address> {
        self.sequencer_registry.get_preferred_sequencer(working_set)
    }
}

/// Empty module implementation
impl<S: sov_modules_api::Spec, Da: sov_modules_api::DaSpec> KernelModule for BlobStorage<S, Da> {
    type Spec = S;
    type Config = ();

    fn genesis_unchecked(
        &self,
        _config: &Self::Config,
        _working_set: &mut KernelWorkingSet<'_, Self::Spec>,
    ) -> Result<(), sov_modules_api::Error> {
        Ok(())
    }
}

/// Contains raw transactions obtained from the DA blob, plus metadata required for blobs
/// from the preferred sequencer.
#[derive(Debug, PartialEq, Clone, BorshDeserialize, BorshSerialize, Serialize, Deserialize)]
pub struct PreferredBatch {
    /// The sequence number of the batch. The rollup attempts to process batches in order by sequence number.
    pub sequence_number: u64,
    /// The actual transactions of the batch
    pub txs: Vec<RawTx>,

    /// The number of virtual slots to advance fter processing the batch. Minimum 1.
    pub virtual_slots_to_advance: u8,
}

/// A preferred batch and the ID (hash) of the blob that it was deserialized from
#[derive(Debug, PartialEq, Clone, BorshDeserialize, BorshSerialize, Serialize, Deserialize)]
pub struct PreferredBatchWithId {
    /// Raw transactions.
    pub inner: PreferredBatch,
    /// The ID of the batch, carried over from the DA layer. This is the hash of the blob which contained the batch.
    pub id: [u8; 32],
}
