use std::fmt::{Display, Formatter, Result};

static INDENT: &str = "    ";

fn indent(levels: u32, f: &mut Formatter<'_>) -> Result {
    for _ in 0..levels {
        write!(f, "{INDENT}")?;
    }
    Ok(())
}

#[derive(Debug)]
pub enum Ty {
    Bool,
    Uint256,
    Ident(String),
    Array(Box<Ty>, usize),
}

impl Display for Ty {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        match self {
            Ty::Bool => write!(f, "bool"),
            Ty::Uint256 => write!(f, "uint256"),
            Ty::Ident(i) => write!(f, "{i}"),
            Ty::Array(ty, len) => write!(f, "{ty}[{len}]"),
        }
    }
}

#[derive(Debug)]
pub struct Field {
    pub name: String,
    pub ty: Ty,
}

impl Display for Field {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{} {};", self.ty, self.name)
    }
}

#[derive(Debug)]
pub struct Struct {
    pub name: String,
    pub fields: Vec<Field>,
}

impl Struct {
    fn to_string(&self, levels: u32, f: &mut Formatter<'_>) -> Result {
        let Struct { name, fields } = self;
        indent(levels, f)?;
        writeln!(f, "struct {name} {{")?;
        for field in fields {
            indent(levels + 1, f)?;
            writeln!(f, "{field}")?;
        }
        indent(levels, f)?;
        writeln!(f, "}}")
    }
}

impl Display for Struct {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        self.to_string(0, f)
    }
}

#[derive(Debug)]
pub struct Block(pub Vec<Struct>);

impl Display for Block {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        writeln!(f, "// This file is generated by the universal wallet sol schema builder. Do not edit manually")?;
        writeln!(f, "use alloy_sol_types::sol;")?;
        writeln!(f, "sol! {{")?;
        for item in &self.0 {
            item.to_string(1, f)?;
        }
        writeln!(f, "}}")?;
        Ok(())
    }
}
