use std::fmt::{Display, Formatter, Result};

static INDENT: &str = "    ";

fn indent(levels: u32, f: &mut Formatter<'_>) -> Result {
    for _ in 0..levels {
        write!(f, "{}", INDENT)?;
    }
    Ok(())
}

pub enum Ty {
    Uint256,
    Ident(String),
}

impl Display for Ty {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        match self {
            Ty::Uint256 => write!(f, "uint256"),
            Ty::Ident(i) => write!(f, "{i}"),
        }
    }
}

pub struct Field {
    pub name: String,
    pub ty: Ty,
}

impl Display for Field {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{} {};", self.ty, self.name)
    }
}

pub enum Item {
    Struct { name: String, fields: Vec<Field> },
}

impl Item {
    fn to_string(&self, levels: u32, f: &mut Formatter<'_>) -> Result {
        match self {
            Item::Struct { name, fields } => {
                indent(levels, f)?;
                writeln!(f, "struct {} {{", name)?;
                for field in fields {
                    indent(levels + 1, f)?;
                    writeln!(f, "{}", field)?;
                }
                indent(levels + 1, f)?;
                write!(f, "}}")
            }
        }
    }
}

impl Display for Item {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        self.to_string(0, f)
    }
}

pub struct Block(pub Vec<Item>);

impl Display for Block {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        writeln!(f, "// This file is generated by the universal wallet sol schema builder. Do not edit manually")?;
        writeln!(f, "sol! {{")?;
        for item in &self.0 {
            item.to_string(1, f)?;
        }
        writeln!(f, "}}")?;
        Ok(())
    }
}
