use celestia_types::nmt::Namespace;

pub const ROLLUP_BATCH_NAMESPACE: Namespace = Namespace::const_v0(*b"\0\0sov-test");
pub const ROLLUP_PROOF_NAMESPACE: Namespace = Namespace::const_v0(*b"sov-test-p");
pub(crate) mod files {
    use std::fs::File;
    use std::path::{Path, PathBuf};

    use anyhow::Context;
    use celestia_types::nmt::Namespace;
    use celestia_types::row_namespace_data::NamespaceData;
    use celestia_types::ExtendedHeader;
    use serde::de::DeserializeOwned;

    use super::*;
    use crate::types::{FilteredCelestiaBlock, NamespaceWithShares};

    // The files are generated by printing the data in the `CelestiaService::get_block_at`` method.
    pub const HEADER_JSON: &str = "header.json";
    pub const ROLLUP_BATCH_ROWS_JSON: &str = "rollup_batch_rows.json";
    pub const ROLLUP_PROOF_ROWS_JSON: &str = "rollup_proof_rows.json";
    pub const ETX_ROWS_JSON: &str = "etx_rows.json";

    pub mod with_rollup_proof_data {
        use super::*;
        pub const DATA_PATH: &str = "test_data/block_with_rollup_proof_data";

        pub fn filtered_block() -> FilteredCelestiaBlock {
            let path = make_test_path(DATA_PATH);
            filtered_block_from_path(ROLLUP_BATCH_NAMESPACE, ROLLUP_PROOF_NAMESPACE, &path).unwrap()
        }
    }

    pub mod with_rollup_batch_data {
        use super::*;
        pub const DATA_PATH: &str = "test_data/block_with_rollup_batch_data";

        pub fn filtered_block() -> FilteredCelestiaBlock {
            let path = make_test_path(DATA_PATH);
            filtered_block_from_path(ROLLUP_BATCH_NAMESPACE, ROLLUP_PROOF_NAMESPACE, &path).unwrap()
        }
    }

    pub mod with_namespace_padding {
        use super::*;
        pub const DATA_PATH: &str = "test_data/block_with_namespace_padding";

        pub const ROLLUP_BATCH_NAMESPACE: Namespace = Namespace::const_v0(*b"sov-roll05");
        pub const ROLLUP_PROOF_NAMESPACE: Namespace = Namespace::const_v0(*b"sov-prov05");

        pub fn filtered_block() -> FilteredCelestiaBlock {
            let path = make_test_path(DATA_PATH);
            // sov-roll05 is the demo testnet rollup that faced the padding issue
            // We use the exact mocha testnet block that caused the breakage
            filtered_block_from_path(ROLLUP_BATCH_NAMESPACE, ROLLUP_PROOF_NAMESPACE, &path).unwrap()
        }
    }

    pub mod without_rollup_batch_data {
        use super::*;
        const DATA_PATH: &str = "test_data/block_without_rollup_batch_data";

        pub fn filtered_block() -> FilteredCelestiaBlock {
            let path = make_test_path(DATA_PATH);
            filtered_block_from_path(ROLLUP_BATCH_NAMESPACE, ROLLUP_PROOF_NAMESPACE, &path).unwrap()
        }
    }

    fn filtered_block_from_path(
        batch_namespace: Namespace,
        proof_namespace: Namespace,
        path: &Path,
    ) -> anyhow::Result<FilteredCelestiaBlock> {
        let header: ExtendedHeader = load_from_file(path, HEADER_JSON)?;
        let rollup_batch_rows: NamespaceData = load_from_file(path, ROLLUP_BATCH_ROWS_JSON)?;
        let rollup_proof_rows: NamespaceData = load_from_file(path, ROLLUP_PROOF_ROWS_JSON)?;
        let etx_rows: NamespaceData = load_from_file(path, ETX_ROWS_JSON)?;

        let rollup_batch_shares = NamespaceWithShares {
            namespace: batch_namespace,
            rows: rollup_batch_rows,
        };

        let rollup_proof_shares = NamespaceWithShares {
            namespace: proof_namespace,
            rows: rollup_proof_rows,
        };

        FilteredCelestiaBlock::new(rollup_batch_shares, rollup_proof_shares, header, etx_rows)
    }

    pub(crate) fn make_test_path(data_path: &str) -> PathBuf {
        let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        path.push(Path::new(data_path));
        path
    }

    pub(crate) fn load_from_file<T: DeserializeOwned>(
        path: &Path,
        name: &str,
    ) -> anyhow::Result<T> {
        let path = path.join(name);
        let file = File::open(&path).context(format!("Failed to open {}", path.display()))?;
        serde_json::from_reader(file).context(format!("Failed to parse {}", path.display()))
    }
}

pub(crate) mod serialization {
    use std::num::NonZero;

    use celestia_types::row_namespace_data::NamespaceData;
    use sov_rollup_interface::da::{RelevantBlobs, RelevantProofs};
    use sov_rollup_interface::node::da::DaService;

    use super::*;
    use crate::types::{BlobWithSender, FilteredCelestiaBlock};
    use crate::verifier::proofs::EtxProof;
    use crate::verifier::RollupParams;
    use crate::{CelestiaConfig, CelestiaService};

    pub(crate) async fn get_test_da_service(port: u16) -> CelestiaService {
        CelestiaService::new(
            CelestiaConfig {
                celestia_rpc_auth_token: "TEST".to_string(),
                celestia_rpc_address: format!("http://127.0.0.1:{}", port),
                max_celestia_response_body_size: NonZero::new(100_000).unwrap(),
                celestia_rpc_timeout_seconds: NonZero::new(10).unwrap(),
                safe_lead_time_ms: 500,
            },
            RollupParams {
                rollup_batch_namespace: ROLLUP_BATCH_NAMESPACE,
                rollup_proof_namespace: ROLLUP_PROOF_NAMESPACE,
            },
        )
        .await
    }

    pub(crate) async fn test_block_serialization(
        da_service: &CelestiaService,
        block: FilteredCelestiaBlock,
    ) {
        // Block itself
        let serialized_bincode_block =
            bincode::serialize(&block).expect("block bincode serialization failed");
        let deserialize_bincode_block =
            bincode::deserialize::<FilteredCelestiaBlock>(&serialized_bincode_block)
                .expect("block bincode deserialization failed");
        assert_eq!(block, deserialize_bincode_block);

        let serialized_risc0_block =
            risc0_zkvm::serde::to_vec(&block).expect("block risc0 serialization failed");
        let deserialized_risc0_block: FilteredCelestiaBlock =
            risc0_zkvm::serde::from_slice(&serialized_risc0_block)
                .expect("block risc0 deserialization failed");
        assert_eq!(block, deserialized_risc0_block);

        // Relevant blobs
        let relevant_blobs = da_service.extract_relevant_blobs(&block);

        let serialized_bincode_relevant_blobs = bincode::serialize(&relevant_blobs)
            .expect("relevant blobs bincode serialization failed");
        let deserialized_bincode_relevant_blobs: RelevantBlobs<BlobWithSender> =
            bincode::deserialize(&serialized_bincode_relevant_blobs)
                .expect("relevant blobs bincode deserialization failed");
        assert_eq!(
            relevant_blobs.batch_blobs,
            deserialized_bincode_relevant_blobs.batch_blobs
        );
        assert_eq!(
            relevant_blobs.proof_blobs,
            deserialized_bincode_relevant_blobs.proof_blobs
        );

        let serialized_risc0_relevant_blobs = risc0_zkvm::serde::to_vec(&relevant_blobs)
            .expect("relevant blobs risc0 serialization failed");
        let deserialized_risc0_relevant_blobs: RelevantBlobs<BlobWithSender> =
            risc0_zkvm::serde::from_slice(&serialized_risc0_relevant_blobs)
                .expect("relevant blobs risc0 deserialization failed");

        assert_eq!(
            relevant_blobs.batch_blobs,
            deserialized_risc0_relevant_blobs.batch_blobs
        );
        assert_eq!(
            relevant_blobs.proof_blobs,
            deserialized_risc0_relevant_blobs.proof_blobs
        );

        // Extraction proof
        let extraction_proof = da_service
            .get_extraction_proof(&block, &relevant_blobs)
            .await;

        let serialized_bincode_extraction_proof = bincode::serialize(&extraction_proof)
            .expect("extraction proof bincode serialization failed");
        let deserialized_bincode_extraction_proof: RelevantProofs<Vec<EtxProof>, NamespaceData> =
            bincode::deserialize(&serialized_bincode_extraction_proof)
                .expect("extraction proof bincode deserialization failed");
        compare_ext_proof(&extraction_proof, &deserialized_bincode_extraction_proof);

        let serialized_risc0_extraction_proof = risc0_zkvm::serde::to_vec(&extraction_proof)
            .expect("extraction proof risc0 serialization failed");
        let deserialized_risc0_extraction_proof: RelevantProofs<Vec<EtxProof>, NamespaceData> =
            risc0_zkvm::serde::from_slice(&serialized_risc0_extraction_proof)
                .expect("extraction proof risc0 deserialization failed");
        compare_ext_proof(&extraction_proof, &deserialized_risc0_extraction_proof);
    }

    fn compare_ext_proof(
        expected: &RelevantProofs<Vec<EtxProof>, NamespaceData>,
        deserialized: &RelevantProofs<Vec<EtxProof>, NamespaceData>,
    ) {
        assert_eq!(
            expected.proof.inclusion_proof,
            deserialized.proof.inclusion_proof
        );
        assert_eq!(
            expected.proof.completeness_proof,
            deserialized.proof.completeness_proof
        );
        assert_eq!(
            expected.batch.inclusion_proof,
            deserialized.batch.inclusion_proof
        );
        assert_eq!(
            expected.batch.completeness_proof,
            deserialized.batch.completeness_proof
        );
    }
}
