openapi: "3.0.2"
info:
  title: Sovereign SDK rollup API
  version: 0.1.0
  description: |
    This is the JSON API for the Sovereign SDK rollup functionality.
    It exists to provide helpful operations to external tooling such as web3 SDKs.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Sovereign Labs
    url: https://github.com/Sovereign-Labs/sovereign-sdk
    email: info@sovereign.xyz
  x-displayName: rollup
servers:
  - url: http://localhost:12346
    description: Localhost
paths:
  /rollup/base-fee-per-gas/latest:
    get:
      summary: Retrieve the latest base fee per gas
      operationId: get_latest_base_fee_per_gas
      tags:
        - Rollup
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/BaseFeePerGas"
                  meta:
                    type: object
                  errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/Error"
                required:
                  - meta
  /rollup/addresses/{address}/dedup:
    get:
      summary: Deduplicate an address
      description: |
        This endpoint retireves deduplication information needed for building transactions.
        The exact shape of the data in the response depends on the implementation of the rollup.
      operationId: address_dedup
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The address to retrieve deduplication information about
      tags:
        - Rollup
      responses:
        "200":
          $ref: "#/components/responses/Dedup"
        "400":
          $ref: "#/components/responses/BadRequest"

  /rollup/simulate:
    post:
      summary: Simulate transaction execution
      operationId: simulate
      tags:
        - Rollup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  $ref: "#/components/schemas/PartialTransaction"
              required:
                - body
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/SimulateExecutionResponse"
                  meta:
                    type: object
                  errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/Error"
                required:
                  - meta

components:
  responses:
    Dedup:
      description: Successfully calculated dedup details for the provided address.
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/RollupAnyJsonValue"
              meta:
                $ref: "#/components/schemas/RollupAnyJsonValue"
            required:
              - data
              - meta
    BadRequest:
      description: The request sent was invalid.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"
              meta:
                $ref: "#/components/schemas/RollupAnyJsonValue"
            required:
              - errors
              - meta
  schemas:
    BaseFeePerGas:
      type: object
      properties:
        base_fee_per_gas:
          $ref: "#/components/schemas/GasPrice"
      required:
        - base_fee_per_gas

    GasPrice:
      description: GasPrice is an array of u64
      type: array
      items:
        type: integer
        format: uint64

    GasUnit:
      description: GasUnit is an array of u64
      type: array
      items:
        type: integer
        format: uint64

    PartialTransaction:
      type: object
      properties:
        sender_pub_key:
          type: string
          format: byte
        nonce:
          type: integer
          format: uint64
        gas_price:
          $ref: "#/components/schemas/GasPrice"
        sequencer:
          type: string
          format: byte
        encoded_call_message:
          type: string
          format: byte
        details:
          $ref: "#/components/schemas/TxDetails"
      required:
        - sender_pub_key
        - nonce
        - encoded_call_message
        - details

    TxDetails:
      type: object
      properties:
        max_priority_fee_bips:
          type: integer
          format: uint64
        max_fee:
          type: integer
          format: uint64
        gas_limit:
          $ref: "#/components/schemas/GasUnit"
        chain_id:
          type: integer
          format: uint64
      required:
        - max_priority_fee_bips
        - max_fee
        - chain_id

    SimulateExecutionResponse:
      type: object
      properties:
        apply_tx_result:
          $ref: "#/components/schemas/ApplyTxResult"
      required:
        - apply_tx_result

    ApplyTxResult:
      type: object
      properties:
        receipt:
          $ref: "#/components/schemas/TxReceiptRollup"
        transaction_consumption:
          $ref: "#/components/schemas/TransactionConsumption"
      required:
        - receipt
        - transaction_consumption

    TransactionConsumption:
      type: object
      properties:
        remaining_funds:
          type: integer
          format: uint64
        base_fee:
          $ref: "#/components/schemas/GasUnit"
        priority_fee:
          type: integer
          format: uint64
        gas_price:
          $ref: "#/components/schemas/GasPrice"
      required:
        - remaining_funds
        - base_fee
        - priority_fee
        - gas_price

    TxReceiptRollup:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: "#/components/schemas/StoredEvent"
        receipt:
          $ref: "#/components/schemas/TxEffect"
      required:
        - events
        - receipt

    StoredEvent:
      type: object
      properties:
        key:
          type: string
          format: byte
        value:
          type: string
          format: byte
      required:
        - key
        - value

    TxEffect:
      type: object
      properties:
        outcome:
          type: string
          enum:
            - successful
            - reverted
            - skipped
        content:
          type: string
          format: byte
      required:
        - outcome
        - content

    RollupAnyJsonValue:
      oneOf:
        - type: string
          title: "String"
        - type: number
          title: "Number"
        - type: boolean
          title: "Boolean"
        - type: array
          title: "Array"
          items:
            x-stainless-any: true
        - type: object
          title: "Object"
          additionalProperties: true

    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: HTTP status code related to this error
        title:
          type: string
        details:
          type: object
      required:
        - status
        - title
        - details
