
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/"
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/guillevalin/.bun/bin/"
      - "/Users/guillevalin/.local/share/solana/install/active_release/bin/"
      - "/Users/guillevalin/.pyenv/shims/"
      - "/Users/guillevalin/.pyenv/bin/"
      - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/guillevalin/.local/bin/"
      - "/Users/guillevalin/.cargo/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
    searched_directories:
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/uname"
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten/uname"
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/Users/guillevalin/.bun/bin/uname"
      - "/Users/guillevalin/.local/share/solana/install/active_release/bin/uname"
      - "/Users/guillevalin/.pyenv/shims/uname"
      - "/Users/guillevalin/.pyenv/bin/uname"
      - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk"
        - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/guillevalin/.bun/bin"
        - "/Users/guillevalin/.local/share/solana/install/active_release/bin"
        - "/Users/guillevalin/.pyenv/shims"
        - "/Users/guillevalin/.pyenv/bin"
        - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/guillevalin/.local/bin"
        - "/Users/guillevalin/.cargo/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/"
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/guillevalin/.bun/bin/"
      - "/Users/guillevalin/.local/share/solana/install/active_release/bin/"
      - "/Users/guillevalin/.pyenv/shims/"
      - "/Users/guillevalin/.pyenv/bin/"
      - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/guillevalin/.local/bin/"
      - "/Users/guillevalin/.cargo/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
    searched_directories:
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/install_name_tool"
      - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten/install_name_tool"
      - "/opt/homebrew/opt/llvm/bin/install_name_tool"
      - "/Users/guillevalin/.bun/bin/install_name_tool"
      - "/Users/guillevalin/.local/share/solana/install/active_release/bin/install_name_tool"
      - "/Users/guillevalin/.pyenv/shims/install_name_tool"
      - "/Users/guillevalin/.pyenv/bin/install_name_tool"
      - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk"
        - "/Users/guillevalin/Documents/dcSpark/ligero-vm/emsdk/upstream/emscripten"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/guillevalin/.bun/bin"
        - "/Users/guillevalin/.local/share/solana/install/active_release/bin"
        - "/Users/guillevalin/.pyenv/shims"
        - "/Users/guillevalin/.pyenv/bin"
        - "/Users/guillevalin/.nvm/versions/node/v24.6.0/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/guillevalin/.local/bin"
        - "/Users/guillevalin/.cargo/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
