//! A client for the Sovereign SDK ledger JSON API, generated by
//! [`progenitor`].

use anyhow::Context;
use base64::prelude::*;
use borsh::BorshSerialize;
use futures::stream::BoxStream;
use futures::StreamExt;
use sov_rollup_interface::node::ledger_api::{FinalityStatus, IncludeChildren};
use sov_rollup_interface::zk::aggregated_proof;
use sov_rollup_interface::TxHash;
use tokio_tungstenite::connect_async;
use tokio_tungstenite::tungstenite::{Error as WsError, Message};
use types::AcceptTxResponse;
pub extern crate tokio_tungstenite;

pub type WsSubscription<T> = Result<BoxStream<'static, anyhow::Result<T>>, WsError>;

progenitor::generate_api!(
    spec = "./openapi-v3.yaml",
    derives = [Debug, Clone, PartialEq],
);

/// Custom WebSocket extensions and extra utilities, in addition to the
/// [`Client`] generated by [`progenitor`].
impl Client {
    pub async fn subscribe_slots_with_children(
        &self,
        include_children: IncludeChildren,
    ) -> WsSubscription<types::Slot> {
        self.subscribe_to_ws(&format!(
            "/ledger/slots/latest/ws?children={include_children}"
        ))
        .await
    }

    pub async fn subscribe_slots(&self) -> WsSubscription<types::Slot> {
        self.subscribe_slots_with_children(IncludeChildren::default())
            .await
    }

    pub async fn subscribe_finalized_slots_with_children(
        &self,
        include_children: IncludeChildren,
    ) -> WsSubscription<types::Slot> {
        self.subscribe_to_ws(&format!(
            "/ledger/slots/finalized/ws?children={include_children}"
        ))
        .await
    }

    pub async fn subscribe_finalized_slots(&self) -> WsSubscription<types::Slot> {
        self.subscribe_finalized_slots_with_children(IncludeChildren::default())
            .await
    }

    pub async fn subscribe_aggregated_proof(&self) -> WsSubscription<types::AggregatedProof> {
        self.subscribe_to_ws("/ledger/aggregated-proofs/latest/ws")
            .await
    }
    /// Sends transactions to the sequencer for immediate publication.
    pub async fn publish_batch_with_serialized_txs<Tx: BorshSerialize>(
        &self,
        txs: &[Tx],
    ) -> Result<types::SubmitBatchReceipt, Error<types::PublishBatchResponse>> {
        let mut txs_b64 = Vec::with_capacity(txs.len());

        for tx in txs {
            let tx_bytes =
                borsh::to_vec(tx).map_err(|err| Error::InvalidRequest(err.to_string()))?;

            txs_b64.push(BASE64_STANDARD.encode(&tx_bytes));
        }

        let publish_batch_response = self
            .publish_batch(&types::PublishBatchBody {
                transactions: txs_b64,
            })
            .await?;
        Ok(publish_batch_response.data.clone().unwrap())
    }

    /// Sends transactions to the sequencer for later publication.
    pub async fn send_txs_to_sequencer<Tx: BorshSerialize>(
        &self,
        txs: &[Tx],
    ) -> Result<Vec<ResponseValue<AcceptTxResponse>>, Error<types::AcceptTxResponse>> {
        let mut receipts = Vec::with_capacity(txs.len());

        for tx in txs {
            let tx_bytes =
                borsh::to_vec(tx).map_err(|err| Error::InvalidRequest(err.to_string()))?;
            let tx_b64 = BASE64_STANDARD.encode(&tx_bytes);

            receipts.push(
                self.accept_tx(&types::AcceptTxBody { body: tx_b64 })
                    .await?,
            );
        }

        Ok(receipts)
    }

    pub async fn subscribe_to_tx_status_updates(
        &self,
        tx_hash: TxHash,
    ) -> WsSubscription<types::TxInfo> {
        self.subscribe_to_ws(&format!("/sequencer/txs/{}/ws", tx_hash))
            .await
    }

    async fn subscribe_to_ws<T: serde::de::DeserializeOwned>(
        &self,
        path: &str,
    ) -> WsSubscription<T> {
        // The base URL can't be used for WebSocket connections; we need to
        // change the protocol.
        let url = format!("{}{}", self.baseurl(), path).replace("http://", "ws://");

        let (ws, _) = connect_async(url).await?;

        Ok(ws
            .filter_map(|msg| async {
                match msg {
                    Ok(Message::Text(text)) => match serde_json::from_str(&text) {
                        Ok(tx_status) => Some(Ok(tx_status)),
                        Err(err) => Some(Err(anyhow::anyhow!(
                            "failed to deserialize JSON {} into type: {}",
                            text,
                            err
                        ))),
                    },
                    Ok(Message::Binary(msg)) => {
                        tracing::warn!(
                            ?msg,
                            "Received unsupported binary message from WebSocket connection"
                        );
                        None
                    }
                    // All other kinds of messages are ignored because
                    // `tokio-tungstenite` ought to handle all
                    // meta-communication messages (ping, pong, clonse) for us anyway.
                    Ok(_) => None,
                    // Errors are not handled here but passed to the caller.
                    Err(err) => Some(Err(anyhow::anyhow!("{}", err))),
                }
            })
            .boxed())
    }
}

impl TryInto<aggregated_proof::SerializedAggregatedProof> for types::AggregatedProof {
    type Error = anyhow::Error;

    fn try_into(self) -> anyhow::Result<aggregated_proof::SerializedAggregatedProof> {
        Ok(aggregated_proof::SerializedAggregatedProof {
            raw_aggregated_proof: decode_b64(&self.proof)?,
        })
    }
}

fn decode_b64(data: &str) -> anyhow::Result<Vec<u8>> {
    BASE64_STANDARD
        .decode(data)
        .context("Failed to decode base64 data in aggregated proof response")
}

impl From<types::SlotFinalityStatus> for FinalityStatus {
    fn from(value: types::SlotFinalityStatus) -> Self {
        match value {
            types::SlotFinalityStatus::Finalized => FinalityStatus::Finalized,
            types::SlotFinalityStatus::Pending => FinalityStatus::Pending,
        }
    }
}
