use std::fs::File;
use std::io::{self, Write};
use std::process::Command;

use demo_stf::runtime::{Runtime, RuntimeCall};
use sov_address::MultiAddressEvm;
use sov_mock_da::MockDaSpec;
use sov_mock_zkvm::MockZkvm;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::schemars::schema_for;
use sov_zkvm_utils::should_skip_guest_build;

type S = sov_modules_api::configurable_spec::ConfigurableSpec<
    MockDaSpec,
    MockZkvm,
    MockZkvm,
    MultiAddressEvm,
    Native,
>;

fn try_set_commit_hash_env() {
    if let Ok(output) = Command::new("git").args(["rev-parse", "HEAD"]).output() {
        if output.status.success() {
            let hash = String::from_utf8_lossy(&output.stdout).trim().to_string();
            println!("cargo:rustc-env=GIT_COMMIT_HASH={hash}");
        }
    }
}

fn main() -> io::Result<()> {
    println!("cargo::rerun-if-env-changed=SKIP_GUEST_BUILD");
    println!("cargo::rerun-if-env-changed=SOV_PROVER_MODE");
    println!("cargo::rustc-check-cfg=cfg(skip_guest_build)");
    println!("cargo:rerun-if-changed=NULL");

    // It will be true only if SKIP_GUEST_BUILD is 1 or true
    if should_skip_guest_build("any-zkvm") {
        println!("cargo::rustc-cfg=skip_guest_build");
    }

    let schema = sov_modules_api::runtime::get_runtime_schema::<S, Runtime<S>>()
        .expect("Failed to get schema");

    let schema_json_string = serde_json::to_string_pretty(&schema)?;
    let mut json_file = File::create("demo-rollup-schema.json")?;
    json_file.write_all(schema_json_string.as_bytes())?;
    json_file.write_all(b"\n")?;

    let borsh_file = File::create("demo-rollup-schema.bin")?;
    borsh::to_writer(borsh_file, &schema)?;

    let chain_hash = schema.cached_chain_hash().unwrap();
    let mut generated_file = File::create("autogenerated.rs")?;
    write!(
        &mut generated_file,
        "pub const CHAIN_HASH: [u8; 32] = {chain_hash:?};\n\n"
    )?;
    write!(
        &mut generated_file,
        "#[allow(dead_code)]\npub const SCHEMA_JSON: &str = r#\"{schema_json_string}\"#;\n"
    )?;

    // usage with quicktype (after removing invalid empty `NotInstantiable` enum)
    // quicktype -s schema runtime_call.json -o runtime_call.ts
    // Resulting TypeScript file will contain strong types for the runtimes call messages
    let mut runtime_call = File::create("runtime_call.json").unwrap();
    let schema = schema_for!(RuntimeCall<S>);
    let schema_str = serde_json::to_string_pretty(&schema).unwrap();
    runtime_call.write_all(schema_str.as_bytes()).unwrap();
    runtime_call.write_all(b"\n")?;

    try_set_commit_hash_env();

    Ok(())
}
