use std::hash::Hasher;

use jsonrpsee::core::RpcResult;
use sov_modules_api::macros::rpc_gen;
use sov_modules_api::{ModuleInfo, Spec, WorkingSet};
use sov_state::ZkStorage;
use sov_test_utils::ZkTestSpec;

#[derive(ModuleInfo)]
pub struct TestStruct<S: ::sov_modules_api::Spec, D>
where
    D: std::hash::Hash
        + std::clone::Clone
        + borsh::BorshSerialize
        + borsh::BorshDeserialize
        + serde::Serialize
        + serde::de::DeserializeOwned
        + 'static,
{
    #[address]
    pub(crate) address: S::Address,
    #[state]
    pub(crate) data: ::sov_modules_api::StateValue<D>,
}

#[rpc_gen(client, server, namespace = "test")]
impl<S: sov_modules_api::Spec, D> TestStruct<S, D>
where
    D: std::hash::Hash
        + std::clone::Clone
        + borsh::BorshSerialize
        + borsh::BorshDeserialize
        + serde::Serialize
        + serde::de::DeserializeOwned
        + 'static,
{
    #[rpc_method(name = "firstMethod")]
    pub fn first_method(&self, _working_set: &mut WorkingSet<S>) -> RpcResult<u32> {
        Ok(11)
    }

    #[rpc_method(name = "secondMethod")]
    pub fn second_method(
        &self,
        result: D,
        _working_set: &mut WorkingSet<S>,
    ) -> RpcResult<(D, u64)> {
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        let value = result.clone();
        value.hash(&mut hasher);
        let hashed_value = hasher.finish();

        Ok((value, hashed_value))
    }
}

pub struct TestRuntime<S: Spec> {
    test_struct: TestStruct<S, u32>,
}

// This is generated by a macro annotating the state transition runner,
// but we do not have that in scope here so generating the struct manually.
struct RpcStorage<S: Spec> {
    pub storage: ::jsonrpsee::tokio::sync::watch::Receiver<S::Storage>,
}

impl TestStructRpcImpl<ZkTestSpec, u32> for RpcStorage<ZkTestSpec> {
    fn get_working_set(&self) -> sov_modules_api::WorkingSet<ZkTestSpec> {
        let storage = self.storage.borrow().clone();
        sov_modules_api::WorkingSet::new(storage)
    }
}

fn main() {
    let storage = ZkStorage::new();
    let r: RpcStorage<ZkTestSpec> = RpcStorage {
        storage: ::jsonrpsee::tokio::sync::watch::Sender::new(storage).subscribe(),
    };
    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec, u32>>::first_method(&r)
                .unwrap();
        assert_eq!(result, 11);
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec, u32>>::second_method(&r, 22)
                .unwrap();
        assert_eq!(result, (22, 15733059416522709050));
    }

    println!("All tests passed!");
}
