use jsonrpsee::core::RpcResult;
use sov_modules_api::macros::rpc_gen;
use sov_modules_api::{ModuleInfo, Spec, WorkingSet};
use sov_state::ZkStorage;
use sov_test_utils::ZkTestSpec;

#[derive(ModuleInfo)]
pub struct TestStruct<S: ::sov_modules_api::Spec> {
    #[address]
    pub(crate) address: S::Address,
}

#[rpc_gen(client, server, namespace = "test")]
impl<S: sov_modules_api::Spec> TestStruct<S> {
    #[rpc_method(name = "firstMethod")]
    pub fn first_method(&self, _working_set: &mut WorkingSet<S>) -> RpcResult<u32> {
        Ok(11)
    }

    #[rpc_method(name = "secondMethod")]
    pub fn second_method(&self, result: u32, _working_set: &mut WorkingSet<S>) -> RpcResult<u32> {
        Ok(result)
    }

    #[rpc_method(name = "thirdMethod")]
    pub fn third_method(&self, result: u32) -> RpcResult<u32> {
        Ok(result)
    }

    #[rpc_method(name = "fourthMethod")]
    pub fn fourth_method(&self, _working_set: &mut WorkingSet<S>, result: u32) -> RpcResult<u32> {
        Ok(result)
    }
}

pub struct TestRuntime<S: Spec> {
    test_struct: TestStruct<S>,
}

// This is generated by a macro annotating the state transition runner,
// but we do not have that in scope here so generating the struct manually.
struct RpcStorage<S: Spec> {
    pub storage: ::std::sync::Arc<::std::sync::RwLock<S::Storage>>,
}

impl TestStructRpcImpl<ZkTestSpec> for RpcStorage<ZkTestSpec> {
    fn get_working_set(&self) -> ::sov_modules_api::WorkingSet<ZkTestSpec> {
        let storage = {
            let current_storage = self.storage.read().unwrap().clone();
            current_storage
        };
        ::sov_modules_api::WorkingSet::new(storage)
    }
}

fn main() {
    let storage = std::sync::Arc::new(std::sync::RwLock::new(ZkStorage::new()));
    let r: RpcStorage<ZkTestSpec> = RpcStorage {
        storage: storage.clone(),
    };
    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::first_method(&r)
                .unwrap();
        assert_eq!(result, 11);
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::second_method(
                &r, 22,
            )
            .unwrap();
        assert_eq!(result, 22);
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::third_method(&r, 33)
                .unwrap();
        assert_eq!(result, 33);
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::fourth_method(
                &r, 44,
            )
            .unwrap();
        assert_eq!(result, 44);
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::health(&r).unwrap();
        assert_eq!(result, ());
    }

    {
        let result =
            <RpcStorage<ZkTestSpec> as TestStructRpcServer<ZkTestSpec>>::module_address(&r)
                .unwrap();
        assert_eq!(
            result,
            "sov1y34qkrqwffa3hmpdzvj0fqc0ahmlgrjf5ltfan9ugt82v5ej6lkshg9ypu"
        );
    }

    println!("All tests passed!");
}
