name: "Constant override checks"
on:
  schedule:
    # At 10:00am UTC every day.
    # See:
    # - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # - https://crontab.guru/
    - cron: "0 10 * * *"
  # Allow manual triggering: <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch>.
  workflow_dispatch:

jobs:
